### PR TITLE
Fix Tesla middlewares

### LINKED ISSUE #36: [Tesla-Middlewares] Can not write functions in config
So... I did not make a release when testing the Tesla middlewares PR.

This error raises when a function is in a config file:
`** (Mix) Could not read configuration file. It likely has invalid configuration terms such as functions, references, and pids. Please make sure your configuration is made of numbers, atoms, strings, maps, tuples and lists. Reason: {3, :erl_parse, ['syntax error before: ', 'Fun']}`

As you can see the config requires a function in the case of the [Tesla.Middleware.Retry](https://github.com/Ironjanowar/spotify_uri_bot/blob/96ef7ed58c7e761c4a729c2ba8f285a9820b7eb8/config/config.exs#L8-L19)

### PR DESCRIPTION
**Pull request by Ironjanowar**
This tries to fix #36

### CODE REVIEW

File: lib/ex_gram/adapter/tesla.ex [hunk 1]
```diff
@@ -111,7 +113,29 @@ if Code.ensure_loaded?(Tesla) do
...
-    defp custom_middlewares(),
-      do: Application.get_env(:ex_gram, __MODULE__, [])[:middlewares] || []
+    defp format_middleware({m, f, a}) do
+      case apply(m, f, a) do
+        {_, _} = middleware -> {:ok, middleware}
+        _ -> :error
+      end
+    end
+
+    defp format_middleware({_, _} = mf), do: mf
```
Comment (rockneurotiko) [inline lib/ex_gram/adapter/tesla.ex]: This should return `{:ok, mf}` right?

File: lib/ex_gram/adapter/tesla.ex [hunk 2]
```diff
@@ -111,7 +113,29 @@ if Code.ensure_loaded?(Tesla) do
...
+    defp format_middleware(_), do: :error
+
+    defp custom_middlewares() do
+      (Application.get_env(:ex_gram, __MODULE__, [])[:middlewares] || [])
```
Comment (rockneurotiko) [inline lib/ex_gram/adapter/tesla.ex]: Save this to a variable, I think having parenthesis before a pipe doesn't look good

File: lib/ex_gram/adapter/tesla.ex [hunk 3]
```diff
@@ -111,7 +113,29 @@ if Code.ensure_loaded?(Tesla) do
...
+      |> Enum.reduce([], fn elem, acc ->
+        case format_middleware(elem) do
+          {:ok, middleware} ->
+            IO.inspect(middleware)
```
Comment (rockneurotiko) [inline lib/ex_gram/adapter/tesla.ex]: :eyes:

File: lib/ex_gram/adapter/tesla.ex [hunk 4]
```diff
@@ -111,7 +113,29 @@ if Code.ensure_loaded?(Tesla) do
...
+            [middleware | acc]
```
Comment (rockneurotiko) [inline lib/ex_gram/adapter/tesla.ex]: Be careful, this will return the middlewares reversed as how it was defined in the config, and the order is important in middlewares

File: lib/ex_gram/adapter/tesla.ex [hunk 5]
```diff
@@ -111,7 +113,29 @@ if Code.ensure_loaded?(Tesla) do
...
+
+          :error ->
+            Logger.debug("Discarded, element is not a middleware: #{inspect(elem)}")
```
Comment (rockneurotiko) [inline lib/ex_gram/adapter/tesla.ex]: Why not a warn?

File: lib/ex_gram/adapter/tesla.ex (hunk 3 above)
Comment (Ironjanowar) [reply lib/ex_gram/adapter/tesla.ex]: Hehe
